module AgenticTesting

using CasualPlots
using DataFrames
using Dates
using Observables
using Bonito

include("gui_testing_utils.jl")
include("casualplots_agent_test_utils.jl")
include("screenshot_generators.jl")
include("screenshot_generators_advanced.jl")
include("screenshot_generators_remaining.jl")

export log_result, verify_session_active, set_opened_file_path
export verify_file_loaded, verify_file_row_count, verify_range_selection
export verify_x_selected, verify_y_selected, verify_y_options_filtered_dom, verify_plot_rendered
export verify_observable_value, verify_format_is_custom, verify_format_is_default
export verify_axis_limits, verify_modal_visible, verify_file_on_disk
export verify_script_runs_cleanly

export get_active_session, wait_for_session, get_active_element_info, get_active_element_id, get_active_element_tag, get_active_element_value, get_dropdown_options
export select_dropdown_value, click_button, click_element_by_text, set_radio_value, toggle_checkbox, get_element_info, get_checkboxes_state
export get_focusable_elements, calculate_tab_distance, calculate_dropdown_keystrokes
export wait_until, wait_for_observable, wait_for_ui_settle


export generate_open_tab_screenshot, generate_dataframe_source_screenshot, generate_xy_source_screenshot, generate_format_tab_barplot_dodged_screenshot, capture_gui_screenshot
export generate_format_tab_barplot_stacked_screenshot, generate_format_tab_limits_screenshot, generate_format_tab_lines_screenshot, generate_plot_pane_maximized_screenshot, generate_save_tab_script_screenshot, generate_table_view_screenshot, generate_line_symbol_plot_screenshot

end # module
